# Generated by Django 4.0.3 on 2022-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_goal_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1),
        ),
    ]
